### ISSUE TITLE
Remove audio from menu

### ISSUE THREAD

**Issue by RobertPeek** [deltanet/adapt-contrib-boxmenu#3]
Audio can be removed as it has been added to the audio extension.

Repo name can be renamed so authoring tool changes may not need to be implemented.

**Comment by dancgray** [comment]
@RobertPeek once the changes are removed is this repo any different from the adaptlearning boxmenu?

**Comment by RobertPeek** [comment]
It has still been customised with the Start/Revisit button functionality.

**Comment by RobertPeek** [comment]
Audio removed now.
