### ISSUE TITLE
Update locking feature

### ISSUE THREAD

**Issue by RobertPeek** [deltanet/adapt-contrib-boxmenu#5]
Update locking feature to fully comply with core framework spec:

[https://github.com/adaptlearning/adapt_framework/wiki/Locking-objects-with-'_isLocked'-and-'_lockType'](https://github.com/adaptlearning/adapt_framework/wiki/Locking-objects-with-'_isLocked'-and-'_lockType')

**Comment by dancgray** [comment]
Fixed with https://github.com/deltanet/adapt-contrib-boxmenu/pull/6
